try:
	print('raising')
	raise Exception()
except:
	print('caught')
