try:
	print('raising')
	raise ValueError('bad value')
except:
	print('caught')
